testing actions

diff --git a/.github/workflows/validate-pull_request.yml b/.github/workflows/validate-pull_request.yml
--- a/.github/workflows/validate-pull_request.yml
+++ b/.github/workflows/validate-pull_request.yml
@@ -44,4 +44,7 @@ jobs:
         run: |
           echo MARK-001
           set -x
-          curl -H "Accept: application/vnd.github.v3+json" "${{github.event.pull_request.url}}/files"
+          test "$(curl --silent https://api.github.com/repos/dhis2-scp/whitelist/pulls/4/files | jq -r '.[].filename')" == "list.csv" || {
+            echo "ERROR: Changed a file other than list.csv"
+            exit 1
+          }
