testing actions

diff --git a/.github/workflows/validate-pull_request.yml b/.github/workflows/validate-pull_request.yml
--- a/.github/workflows/validate-pull_request.yml
+++ b/.github/workflows/validate-pull_request.yml
@@ -33,6 +33,12 @@ jobs:
           pwd
           env
 
+      - name: Reject if more than one file is changed
+        if: ${{ github.event.pull_request.changed_files != 1 }}
+        run: |
+          echo "ERROR: more than one file has been changed ..."
+          exit 1
+
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
